SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY,
       SUM(BOOK.PRICE * BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK
INNER JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE BOOK_SALES.SALES_DATE >= '2022-01-01' AND BOOK_SALES.SALES_DATE <= '2022-01-31'
GROUP BY AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID ASC, BOOK.CATEGORY DESC;