-- 코드를 입력하세요
SELECT B.PRODUCT_CODE , SUM(B.PRICE * A.SALES_AMOUNT) as SALES FROM OFFLINE_SALE as A
LEFT JOIN PRODUCT as B
on A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC