-- 코드를 입력하세요
SELECT DISTINCT(A.CAR_ID) FROM CAR_RENTAL_COMPANY_CAR as A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as B
on A.CAR_ID = B.CAR_ID
WHERE START_DATE LIKE '2022-10%' and CAR_TYPE = '세단'
ORDER BY CAR_ID DESC